version: '3'
services:
  localdb:
    build: docker/postgres
    image: localdb
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
      args:
        - UID=${UID}
    image: idetect
    command: sh -c "sleep 5; /usr/bin/supervisord"
    volumes:
      - ./source:/home/idetect
      - ./config/api-supervisord.conf:/etc/supervisord.conf
    ports:
      - 5001:5001
    depends_on:
      - localdb
    env_file: docker.env
    user: ${UID}
  workers:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
      args:
        - UID=${UID}
    image: idetect
    command: sh -c "python3 python/setup.py && /usr/bin/supervisord"
    volumes:
      - ./source:/home/idetect
      - ./logs:/var/log
      - ./config/worker-supervisord.conf:/etc/supervisord.conf
    depends_on:
      - localdb
    env_file: docker.env
    user: ${UID}
  notebooks:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
      args:
        - UID=${UID}
    image: idetect
    command: jupyter notebook --no-browser --ip=0.0.0.0 --port 5002 /home/idetect/notebooks
    volumes:
      - ./source:/home/idetect
    ports:
      - 5002:5002
    depends_on:
      - localdb
    env_file: docker.env
    user: ${UID}
  unittests:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
      args:
        - UID=${UID}
    image: idetect
    command: sh -c 'python3 -m unittest /home/idetect/python/idetect/tests/test_fact_extractor.py'
    volumes:
      - ./source:/home/idetect
    depends_on:
      - localdb
    env_file: docker.env
    user: ${UID}
  cron:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
      args:
        - UID=${UID}
    image: idetect
    user: root
    command: sh -c 'cp /tmp/crontab /etc/cron.d/idetect ; cron -f -L 7'
    volumes:
      - ./source:/home/idetect
      - ./config/crontab:/tmp/crontab
    depends_on:
      - localdb
    env_file: docker.env
