version: '3.4'

x-base-idetect-setup: &x-base-idetect-setup
  image: docker.pkg.github.com/idmc-labs/idetect/idetect:$RELEASE
  env_file: docker.env
  user: ${UID}
  depends_on:
    - localdb


services:

  localdb:
    image: docker.pkg.github.com/idmc-labs/idetect/localdb:$RELEASE
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    <<: *x-base-idetect-setup
    command: sh -c "./scripts/wait-for-it.sh localdb:5432 && /usr/bin/supervisord -c /idetect-configs/api-supervisord.conf"
    ports:
      - 5001:5001

  workers:
    <<: *x-base-idetect-setup
    command: sh -c "python3 python/setup.py && /usr/bin/supervisord -c /idetect-configs/worker-supervisord.conf"
    volumes:
      - ./logs:/var/log

  notebooks:
    <<: *x-base-idetect-setup
    command: jupyter notebook --no-browser --ip=0.0.0.0 --port 5002 /home/idetect/notebooks
    ports:
      - 5002:5002

  cron:
    <<: *x-base-idetect-setup
    user: root
    command: sh -c 'cron -f -L 7 /idetect-configs/crontab'
