version: '3'
services:
  localdb:
    build: docker/postgres
    image: localdb
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
    image: idetect
    command: python3 /home/idetect/python/run_api.py
    volumes:
      - ./source:/home/idetect
    ports:
      - 5001:5001
    depends_on:
      - localdb
    env_file: docker.env
  workers:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
    image: idetect
    command: /usr/bin/supervisord
    volumes:
      - ./source:/home/idetect
      - ./logs:/var/log
      - ./config/supervisord.conf:/etc/supervisord.conf
    depends_on:
      - localdb
    env_file: docker.env
  notebooks:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
    image: idetect
    command: jupyter notebook --no-browser --ip=0.0.0.0 --port 5002 /home/idetect/notebooks
    volumes:
      - ./source:/home/idetect
    ports:
      - 5002:5002
    depends_on:
      - localdb
    env_file: docker.env
#  unittests:
#    build:
#      context: .
#      dockerfile: ./docker/idetect/Dockerfile
#    image: idetect
#    command: sh -c 'python3 -m unittest /home/idetect/python/idetect/tests/test_*.py'
#    volumes:
#      - ./source:/home/idetect
#    depends_on:
#      - localdb
#    env_file: docker.env
  dashboard:
    build:
      context: .
      dockerfile: ./docker/idetect/Dockerfile
    image: idetect
    command: bokeh serve /home/idetect/python/run_dashboard.py
    volumes:
      - ./source:/home/idetect
    ports:
      - 5006:5006
    depends_on:
      - localdb
    env_file: docker.env
